// Generated by gencpp from file hw1/MultiplyTwoInts.msg
// DO NOT EDIT!


#ifndef HW1_MESSAGE_MULTIPLYTWOINTS_H
#define HW1_MESSAGE_MULTIPLYTWOINTS_H

#include <ros/service_traits.h>


#include <hw1/MultiplyTwoIntsRequest.h>
#include <hw1/MultiplyTwoIntsResponse.h>


namespace hw1
{

struct MultiplyTwoInts
{

typedef MultiplyTwoIntsRequest Request;
typedef MultiplyTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MultiplyTwoInts
} // namespace hw1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hw1::MultiplyTwoInts > {
  static const char* value()
  {
    return "d431cae597499d244ef1c576e21358c8";
  }

  static const char* value(const ::hw1::MultiplyTwoInts&) { return value(); }
};

template<>
struct DataType< ::hw1::MultiplyTwoInts > {
  static const char* value()
  {
    return "hw1/MultiplyTwoInts";
  }

  static const char* value(const ::hw1::MultiplyTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::hw1::MultiplyTwoIntsRequest> should match
// service_traits::MD5Sum< ::hw1::MultiplyTwoInts >
template<>
struct MD5Sum< ::hw1::MultiplyTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hw1::MultiplyTwoInts >::value();
  }
  static const char* value(const ::hw1::MultiplyTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hw1::MultiplyTwoIntsRequest> should match
// service_traits::DataType< ::hw1::MultiplyTwoInts >
template<>
struct DataType< ::hw1::MultiplyTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::hw1::MultiplyTwoInts >::value();
  }
  static const char* value(const ::hw1::MultiplyTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hw1::MultiplyTwoIntsResponse> should match
// service_traits::MD5Sum< ::hw1::MultiplyTwoInts >
template<>
struct MD5Sum< ::hw1::MultiplyTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hw1::MultiplyTwoInts >::value();
  }
  static const char* value(const ::hw1::MultiplyTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hw1::MultiplyTwoIntsResponse> should match
// service_traits::DataType< ::hw1::MultiplyTwoInts >
template<>
struct DataType< ::hw1::MultiplyTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::hw1::MultiplyTwoInts >::value();
  }
  static const char* value(const ::hw1::MultiplyTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HW1_MESSAGE_MULTIPLYTWOINTS_H
