// Generated by gencpp from file hw1/MultiplyTwoIntsResponse.msg
// DO NOT EDIT!


#ifndef HW1_MESSAGE_MULTIPLYTWOINTSRESPONSE_H
#define HW1_MESSAGE_MULTIPLYTWOINTSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hw1
{
template <class ContainerAllocator>
struct MultiplyTwoIntsResponse_
{
  typedef MultiplyTwoIntsResponse_<ContainerAllocator> Type;

  MultiplyTwoIntsResponse_()
    : result(0)  {
    }
  MultiplyTwoIntsResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef int64_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::hw1::MultiplyTwoIntsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hw1::MultiplyTwoIntsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MultiplyTwoIntsResponse_

typedef ::hw1::MultiplyTwoIntsResponse_<std::allocator<void> > MultiplyTwoIntsResponse;

typedef boost::shared_ptr< ::hw1::MultiplyTwoIntsResponse > MultiplyTwoIntsResponsePtr;
typedef boost::shared_ptr< ::hw1::MultiplyTwoIntsResponse const> MultiplyTwoIntsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hw1::MultiplyTwoIntsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hw1::MultiplyTwoIntsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hw1::MultiplyTwoIntsResponse_<ContainerAllocator1> & lhs, const ::hw1::MultiplyTwoIntsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hw1::MultiplyTwoIntsResponse_<ContainerAllocator1> & lhs, const ::hw1::MultiplyTwoIntsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hw1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hw1::MultiplyTwoIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hw1::MultiplyTwoIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hw1::MultiplyTwoIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hw1::MultiplyTwoIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hw1::MultiplyTwoIntsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hw1::MultiplyTwoIntsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hw1::MultiplyTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b05623554ab950ed237d43d45f0b4dd";
  }

  static const char* value(const ::hw1::MultiplyTwoIntsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b05623554ab950eULL;
  static const uint64_t static_value2 = 0xd237d43d45f0b4ddULL;
};

template<class ContainerAllocator>
struct DataType< ::hw1::MultiplyTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hw1/MultiplyTwoIntsResponse";
  }

  static const char* value(const ::hw1::MultiplyTwoIntsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hw1::MultiplyTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 result\n"
"\n"
;
  }

  static const char* value(const ::hw1::MultiplyTwoIntsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hw1::MultiplyTwoIntsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MultiplyTwoIntsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hw1::MultiplyTwoIntsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hw1::MultiplyTwoIntsResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int64_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HW1_MESSAGE_MULTIPLYTWOINTSRESPONSE_H
